name: usuario

on:
  push:
    branches:
    - "main"

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        -
          name: Login to Docker
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERVARIABLES }}
            PASSWORD: ${{ secrets.DOCKERTOKEN }}
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
        -
            name: build and push
            uses: docker/build-push-action@v6
            with:
              push: true
              tags: ${{ vars.DOCKERVARIABLES }}/clockbox:latest
